# Generated by Django 5.2.3 on 2025-06-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_found', models.DateField()),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_lost', models.DateField()),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('proof', models.FileField(blank=True, null=True, upload_to='lost_proofs/')),
            ],
        ),
    ]
