# Generated by Django 5.2.3 on 2025-06-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='proof',
        ),
        migrations.AddField(
            model_name='founditem',
            name='item_type',
            field=models.CharField(default='Found', max_length=100),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='lost_items/'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='item_type',
            field=models.CharField(default='Lost', max_length=100),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='found_items/'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
